configs:
- id: st-sw-tag-1
  config:
    name: Star Wars - Tag
    template: ../../../cinema-infrastructure/auto-tag/application-tagging.json
    skip: false
- id: st-sw-tag-2
  config:
    name: Star Wars - Tag 2 - Skipped on Prod
    template: ../../../cinema-infrastructure/auto-tag/application-tagging.json
  groupOverrides:
  - group: production
    override:
      skip: true
  - group: development
    override:
      skip: false
- id: st-sw-tag-3
  config:
    name: Star Wars - Tag 3 - Skipped on Prod
    template: ../../../cinema-infrastructure/auto-tag/application-tagging.json
  groupOverrides:
  - group: production
    override:
      skip: true
  - group: development
    override:
      skip: false
