configs:
- id: report
  config:
    name:
      configType: dashboard
      config: dashboard
      property: id
      type: reference
    template: report.json
    skip: false
  type:
    api: reports
