configs:
- id: demo_slo
  config:
    name: My SLO
    parameters:
      mzone:
        api: management-zone
        config: zone
        property: name
        type: reference
    template: slo.json
    skip: false
