configs:
- id: demo_slo
  config:
    name: My SLO
    parameters:
      mzone:
        api: management-zone
        config: zone
        property: name
        type: reference
      threshold:
        type: value
        value:
          target: 95
          warning: 97.5
    template: slo.json
    skip: false
