configs:
- id: availability
  type:
    api: synthetic-monitor
  config:
    name: Federation Availability
    parameters:
      appId:
        api: application-web
        config: application
        property: id
        type: reference
      host: https://www.google.com
      location: GEOLOCATION-9999453BE4BDB3CD
      managementZoneId:
        api: management-zone
        config: zone
        property: id
        type: reference
      tag:
        api: auto-tag
        config: application-tagging
        property: name
        type: reference
    template: availabilty.json
    skip: false
- id: browser-test
  config:
    name: Borg Availability
    parameters:
      location: GEOLOCATION-9999453BE4BDB3CD
    template: browser-test.json
    skip: false
  type:
    api: synthetic-monitor
