configs:
- id: profile
  config:
    name: Unescaped "Profile" - for things with "quotes"
    template: profile.json
    skip: false
- id: single_tick_profile
  config:
    name: 'Singletick \"Alerting Profile\"'
    template: profile.json
- id: escaped_profile
  config:
    name: Plain escaped \"Alerting Profile\"
    template: profile.json
    skip: false
