configs:
- id: credential
  config:
    name: Sample Credentials
    parameters:
      description: Sample set of credentials for API documentation
      ownerAccessOnly: "true"
      credentialScope: SYNTHETIC
      type: USERNAME_PASSWORD
    template: credential.json
    skip: false
  type:
    api: credential-vault
