configs:
- id: st-sg-tag-1
  config:
    name: Star Gate - Tag 1 - Skipped on Prod
    template: ../../../cinema-infrastructure/auto-tag/application-tagging.json
  groupOverrides:
  - group: development
    override:
      skip: false
  - group: production
    override:
      skip: true
- id: st-sg-tag-2
  config:
    name: Star Gate - Tag 2
    template: ../../../cinema-infrastructure/auto-tag/application-tagging.json
    skip: false
- id: st-sg-tag-3
  config:
    name: Star Gate - Tag 3 - Skipped on Prod
    template: ../../../cinema-infrastructure/auto-tag/application-tagging.json
  groupOverrides:
  - group: development
    override:
      skip: false
  - group: production
    override:
      skip: true
