configs:
- id: slack
  config:
    name: 'Star Trek to #team-star-trek'
    parameters:
      alertingProfileId:
        api: alerting-profile
        config: profile
        property: id
        type: reference
      environment: Env1
    template: subfolder/slack.json
    skip: false
- id: email
  config:
    name: Captain's Log
    parameters:
      alertingProfileId:
        api: alerting-profile
        config: profile
        property: id
        type: reference
      environment: Env1
      receivers:
        type: list
        values:
          - "jean-luc.picard@dynatrace.com"
          - "jim.kirk@dynatrace.com"
    template: subfolder/email.json
    skip: false
- id: email_single_receiver
  config:
    name: "There's only one Captain!'s Log"
    parameters:
      alertingProfileId:
        api: alerting-profile
        config: profile
        property: id
        type: reference
      environment: test-env
      receivers:
        type: list
        values:
          - "james.t.kirk@dynatrace.com"
    template: subfolder/email.json
    skip: false
