configs:
- id: email
  config:
    name: lists are written without escaped quotes
    parameters:
      alertingProfileId:
        api: alerting-profile
        config: profile
        property: id
        type: reference
      environment: Env1
      receivers:
        type: list
        values:
          - "jean-luc.picard@dynatrace.com"
          - "jim.kirk@dynatrace.com"
    template: email.json
